from .FitNet import HintLoss
from .AT import Attention
from .KD import DistillKL
from .SP import Similarity
from .VID import VIDLoss
from .SemCKD import SemCKDLoss
from .DKD import DKDLoss
from .CSKD import CSKDLoss
from .MadKD import MadKDLoss
